export const theme = {
  colors: {
    bg: '#FAF8F5',
    bg2: '#F3EFE9',
    surface: '#FFFFFF',
    surfaceSunk: '#F7F4EF',
    ink: '#1A1816',
    ink2: '#3D3935',
    ink3: '#6B6660',
    ink4: '#9A948D',
    ink5: '#CFC9C1',
    line: '#EBE6DD',
    line2: '#DDD6CB',
    accent: '#5B7058',
    accentSoft: '#E7EEE3',
    accentInk: '#2F3D2C',
    feed: '#B58A4A',
    feedSoft: '#F4EAD8',
    sleep: '#6B7A9A',
    sleepSoft: '#E6E9F1',
    diaper: '#8A7257',
    diaperSoft: '#EDE5DB',
    temp: '#B9624C',
    tempSoft: '#F4DFD6',
    bath: '#5A8A8A',
    bathSoft: '#DDE9E9',
    note: '#7A6F8C',
    noteSoft: '#E8E4EE',
    vitamin: '#9A8540',
    vitaminSoft: '#EFE9D4',
    medicine: '#A5556A',
    medicineSoft: '#F1DEE2',
    white: '#FFFFFF',

    // Backward-compatible aliases for screens that predate the design system.
    background: '#FAF8F5',
    text: '#1A1816',
    muted: '#6B6660',
    primary: '#5B7058',
    border: '#EBE6DD',
  },
  typography: {
    display: {
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 37,
      letterSpacing: 0,
    },
    titleL: {
      fontSize: 26,
      fontWeight: '700' as const,
      lineHeight: 31,
      letterSpacing: 0,
    },
    titleM: {
      fontSize: 20,
      fontWeight: '700' as const,
      lineHeight: 25,
      letterSpacing: 0,
    },
    titleS: {
      fontSize: 16,
      fontWeight: '700' as const,
      lineHeight: 21,
      letterSpacing: 0,
    },
    body: {
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 20,
      letterSpacing: 0,
    },
    bodyS: {
      fontSize: 13,
      fontWeight: '500' as const,
      lineHeight: 19,
      letterSpacing: 0,
    },
    caption: {
      fontSize: 11,
      fontWeight: '500' as const,
      lineHeight: 15,
      letterSpacing: 0.1,
    },
    eyebrow: {
      fontSize: 10,
      fontWeight: '600' as const,
      lineHeight: 13,
      letterSpacing: 0.6,
    },
    mono: {
      fontSize: 13,
      fontWeight: '500' as const,
      lineHeight: 18,
      letterSpacing: 0,
    },
  },
  radii: {
    xs: 6,
    sm: 8,
    md: 12,
    lg: 14,
    xl: 18,
    pill: 99,
  },
  spacing: {
    1: 4,
    2: 6,
    3: 8,
    4: 12,
    5: 16,
    6: 20,
    7: 24,
    8: 32,
  },
  shadows: {
    sm: {
      shadowColor: '#1A1816',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#1A1816',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 2,
    },
    lg: {
      shadowColor: '#1A1816',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.08,
      shadowRadius: 32,
      elevation: 4,
    },
  },
};

export type Theme = typeof theme;
